force-app/main/default/objects/HN_DataObject__c/HN_DataObject__c.object-meta.xml
<CustomObject>
    <description>This Object Holds All the JSON response as record from Hacker News API</description>
    <label>HN_DataObject</label>
    <nameField>
        <label>HN_DataObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HN_DataObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HN_DataObject__c/fields/Descendants__c.field-meta.xml
<CustomField>
    <fullName>Descendants__c</fullName>
    <description>Total number of comments for a story or poll.</description>
    <label>Descendants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HN_DataObject__c/fields/ItemId__c.field-meta.xml
<CustomField>
    <fullName>ItemId__c</fullName>
    <description>Unique Hacker News item ID (Number, External ID, Unique).</description>
    <label>Item ID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HN_DataObject__c/fields/Kids__c.field-meta.xml
<CustomField>
    <fullName>Kids__c</fullName>
    <description>List of IDs of child items.</description>
    <label>Kids</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HN_DataObject__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <description>Title of the item.</description>
    <label>Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HN_DataObject__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <description>Unix timestamp when the item was created.</description>
    <label>Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HN_DataObject__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <description>URL of sites if it mentioned in story</description>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HN_DataObject__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username of the author of the item.</description>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GeneralMethods.cls
public class GeneralMethods {

    public static String getStoryLink(String itemId) {
        return Global_Constants.HN_API + '/v0/item/' + itemId + '.json?print=pretty';
    }

    public static void insertRecord(String itemId) {
        ResponseWrapper story = (ResponseWrapper)JSON.deserialize(getResponse(itemId), ResponseWrapper.class);
        Database.insert(objectMaper(story),false);
    }

    public static String getResponse(String itemId) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();

        request.setEndpoint(GeneralMethods.getStoryLink(itemId));
        request.setMethod('GET');

        HttpResponse response = http.send(request);

        if (response.getStatusCode() == 200) {
            return sanityJSON(response.getBody());
        } else {
            throw new AuraHandledException('Error: ' + response.getStatusCode() + ' ' + response.getStatus());
        }

    }

    public static String getBestStories() {
        Http http = new Http();
        HttpRequest request = new HttpRequest();

        request.setEndpoint(Global_Constants.HN_API_BestStories);
        request.setMethod('GET');

        HttpResponse response = http.send(request);
 
        if (response.getStatusCode() == 200) {
            return response.getBody();
        } else {
            throw new AuraHandledException('Error: ' + response.getStatusCode() + ' ' + response.getStatus());
        }

    }

    public static List < String > getBestStoriesList() {
        Http http = new Http();
        HttpRequest request = new HttpRequest();

        request.setEndpoint(Global_Constants.HN_API_BestStories);
        request.setMethod('GET');

        HttpResponse response = http.send(request);

        if (response.getStatusCode() == 200) {
            return getListString(response.getBody());
        } else {
            throw new AuraHandledException('Error: ' + response.getStatusCode() + ' ' + response.getStatus());
        }

    }

    public static String getTopStories() {
        Http http = new Http();
        HttpRequest request = new HttpRequest();

        request.setEndpoint(Global_Constants.HN_API_TopStories);
        request.setMethod('GET');

        HttpResponse response = http.send(request);

        if (response.getStatusCode() == 200) {
            return response.getBody();
        } else {
            throw new AuraHandledException('Error: ' + response.getStatusCode() + ' ' + response.getStatus());
        }

    }

    public static List < String > getTopStoriesList() {
        Http http = new Http();
        HttpRequest request = new HttpRequest();

        request.setEndpoint(Global_Constants.HN_API_TopStories);
        request.setMethod('GET');

        HttpResponse response = http.send(request);

        if (response.getStatusCode() == 200) {
            return getListString(response.getBody());
        } else {
            throw new AuraHandledException('Error: ' + response.getStatusCode() + ' ' + response.getStatus());
        }

    }

    private static List < Integer > getListInteger(String response) {
        // Convert string to a List of Integers
        return (List < Integer > ) JSON.deserialize(response, List < Integer > .class);
    }

    private static List<String> getListString(String response) {
    // Convert string to a List of String
    return (List<String>) JSON.deserialize(response, List<String>.class);
    }

    private static String sanityJSON(String res){
            if(String.isBlank(res)){
                throw new AuraHandledException('Response is Null or Empty'); 
            }
                // Using quotes + colon ensures we only replace JSON keys
                 return res.replaceAll('(?i)"by"\\s*:', '"postedBy":')
                          .replaceAll('(?i)"id"\\s*:', '"ItemId":')
                          .replaceAll('(?i)"time"\\s*:', '"UnixTime":')
                          .replaceAll('(?i)"type"\\s*:', '"Itemtype":');
    }
	
    Public static HN_DataObject__c objectMaper(ResponseWrapper story){
            HN_DataObject__c obj = new HN_DataObject__c();
            obj.Username__c = story.postedBy;
           
        
            obj.Descendants__c = story.descendants != null ? Integer.valueOf(story.descendants) : 0;
            obj.ItemId__c = story.ItemId != null ? Long.valueOf(story.ItemId) : null;
            
            
            obj.Kids__c = story.kids != null ? String.join(story.kids, ',') : null;
            
            obj.Score__c = story.score != null ? Integer.valueOf(story.score) : 0;
            obj.Time__c =  story.UnixTime != null ? Long.valueOf(story.UnixTime) : null;
            obj.Text__c = story.title;
            obj.Url__c = story.url;
            
            return obj;
    }
    


}